import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ThirdwebProvider } from "thirdweb/react";
import "./globals.css";
import Navbar from "@/components/navbar";

export const poppins = Outfit({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cyber Atlas NFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className + "w-[full]"}>
        <ThirdwebProvider>
          <Navbar />
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
