import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";

export const poppins = Poppins({
 weight:"400",
 subsets:["latin"]
})



export const metadata: Metadata = {
  title: "Axion Enterprise System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar/>
        
        {children}</body>
    </html>
  );
}
